__title__ = 'sparx'
__description__ = 'Simplified Data Munging, Wrangling and Preparing Library'
__url__ = 'http://cleverinsight.co'
__version__ = (0, 0, 1)
__build__ = 0
__author__ = 'Bastin Robins J'
__author_email__ = 'robin@cleverinsight.co'
__license__ = 'Proprietary'
__copyright__ = 'Copyright 2017 CleverInsight'